# Generated by Django 6.0.3 on 2026-03-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(choices=[('odontologo', 'Odontólogo'), ('medico_general', 'Médico General')], max_length=30)),
            ],
        ),
    ]
